-- The one look both sinks draw: a hexagon outline centred in the icon, spinning.
--
-- The mark is ALWAYS our own Texture, on our own frame, so it takes a rotation and a vertex
-- colour. A count never draws the mark; it draws an OCCLUDER over it -- the subject's own
-- icon, centre-cropped -- because an inline escape takes a FontString's alpha and none of its
-- geometric transforms (security-taint-and-restricted-data.md §3.5).
-- Media/ is generated by tool/gen_media.py.

local _, ns = ...

local Look = {}
ns.Look = Look

Look.DEFAULT = "alarm"
Look.FRACTION = 0.72
Look.SPIN_SECONDS = 3

--- MEASURED BY EYE on a live Essential row, which is the only oracle this has. It is above
--- FRACTION so the occluder covers the mark whole, and well inside the corners the Cooldown
--- Manager's mask rounds.
---
--- ⚠ Do NOT "improve" this by arithmetic. A search that minimised how far the drawn size has
--- to round picked 0.78125 over this, on the reasoning that its residual is six times smaller
--- -- and the result visibly RESIZED the icon where this does not. Whatever governs the
--- apparent scale of an inline escape, it is not that residual, and no model here predicts the
--- reading. `/sg tune crop <n>` is how a replacement gets chosen: on the real row, by looking.
Look.OCCLUDE = 0.82

--- Trim, in the FontString's own coordinate space, on the region's anchor rather than in the
--- escape -- the escape's own offsets are integers and this is not one.
---
--- MEASURED BY EYE: an escape centred in a FontString does not draw centred. At a 41-unit
--- draw in a 50-unit frame the art sits ~1.2 units LEFT of the region's centre, which is what
--- `SetPoint` puts back. Consistent with the escape claiming more advance width than its ink
--- fills, the excess trailing -- centring then centres the CLAIM and not the picture.
---
--- ⚠ It is NOT the drawn size rounding to a whole unit. That was the first theory and it is
--- dead: the shift survived a crop of 1.0, where the residual is exactly zero.
--- ⚠ OPEN: whether 1.2 is a constant in units or a fraction of the draw. One value cannot
--- tell them apart. Move the Edit Mode icon-size slider and look again -- if it still lands
--- the offset is constant, and if it drifts it belongs here as a ratio instead.
Look.OCCLUDE_X = 1.2
Look.OCCLUDE_Y = 0

--- Spell icons are 64x64 files. The crop is expressed to `CreateTextureMarkup` as fractions
--- and emitted by it as texels, so this is the number that converts between them.
local ICON_FILE_SIZE = 64

local PALETTE = {
  white = { 1.00, 1.00, 1.00 },
  yellow = { 1.00, 0.82, 0.25 },
  red = { 1.00, 0.32, 0.32 },
  green = { 0.43, 0.91, 0.50 },
  blue = { 0.38, 0.69, 1.00 },
  purple = { 0.77, 0.52, 1.00 },
  orange = { 1.00, 0.58, 0.25 },
  cyan = { 0.37, 0.92, 0.91 },
}

--- A CYCLE is two colours a mark crosses between, and it exists because a single hue cannot
--- be visible on every icon: Paladin's art is yellow-heavy, so a yellow mark on a yellow icon
--- is the one place the glow disappears. Crossing to the opposite side of the wheel means the
--- mark is never the same hue as its background for more than an instant.
---
--- ⚠ Vertex colour is written, not animated. The animation system has no colour type, and the
--- two ways to fake one both fail here: stacking two textures and crossfading their ALPHA
--- would fight the sealed bind for the one channel it owns, and a per-mark OnUpdate needs a
--- frame a texture does not have. So one shared ticker writes every cycling mark instead --
--- it draws and never evaluates, like the sealed families' own.
Look.CYCLE_SECONDS = 1.6
local CYCLES = {
  alarm = { "purple", "yellow" },
}

local cycling = setmetatable({}, { __mode = "k" })
local ticker

local function Lerp(a, b, t)
  return a + (b - a) * t
end

local function Tick()
  -- A triangle wave, so the crossing is even in both directions and neither end holds.
  local phase = (GetTime() % Look.CYCLE_SECONDS) / Look.CYCLE_SECONDS
  local t = phase < 0.5 and phase * 2 or (1 - phase) * 2
  for mark, pair in pairs(cycling) do
    local from, to = PALETTE[pair[1]], PALETTE[pair[2]]
    mark:SetVertexColor(Lerp(from[1], to[1], t), Lerp(from[2], to[2], t),
      Lerp(from[3], to[3], t))
  end
  if next(cycling) == nil and ticker ~= nil then
    ticker:Cancel()
    ticker = nil
  end
end

--- Register a mark as cycling, or take it off. The single writer of a cycling mark's vertex
--- colour is `Tick`, so `SetLit` must hand the mark over rather than tinting it itself.
function Look.SetTint(mark, name)
  local pair = CYCLES[name]
  if pair == nil then
    cycling[mark] = nil
    local rgb = Look.Rgb(name)
    mark:SetVertexColor(rgb[1], rgb[2], rgb[3])
    return
  end
  cycling[mark] = pair
  if ticker == nil then ticker = C_Timer.NewTicker(0.05, Tick) end
end

function Look.IsColor(name)
  return PALETTE[name] ~= nil or CYCLES[name] ~= nil
end

function Look.Names()
  local names = {}
  for name in pairs(PALETTE) do names[#names + 1] = name end
  for name in pairs(CYCLES) do names[#names + 1] = name end
  table.sort(names)
  return names
end

--- A cycle has no single rgb, so anything that needs one -- a preview, a fallback -- takes the
--- first of the pair rather than the default, which may itself be a cycle.
function Look.Rgb(name)
  local pair = CYCLES[name]
  if pair ~= nil then return PALETTE[pair[1]] end
  return PALETTE[name] or PALETTE[CYCLES[Look.DEFAULT] and CYCLES[Look.DEFAULT][1] or Look.DEFAULT]
end

--- One white master, tinted per glow: every mark is our texture, so no hue needs its own file.
Look.MASTER = "Interface\\AddOns\\SmartGlo\\Media\\hex-white"

--- The occluder escape: `fileID` drawn at `fraction` of `width`, cropped to the same centred
--- fraction of the file, so it lands exactly over the pixels it is hiding. The Cooldown
--- Manager draws its icon untrimmed across the whole item rect -- there is no `SetTexCoord`
--- anywhere in Blizzard_CooldownViewer -- so the untrimmed baseline is 0..1 and this is the
--- whole arithmetic.
---
--- Sizes are in the FONTSTRING'S coordinate space, never screen pixels, so `width` must come
--- from `GetWidth()` on the frame the string is drawn in.
--- One candidate: the crop `half` texels either side of the file's centre, and what it costs
--- to draw at `width`. Both ends quantise -- the crop to whole TEXELS of a 64px file, the draw
--- to whole UNITS of the host frame, because `CreateTextureMarkup` emits every field with
--- `%d` -- so `residual` is how far the draw had to round. It is REPORTED, not minimised.
function Look.CropAt(width, half)
  local want = width * (2 * half) / ICON_FILE_SIZE
  local size = math.floor(want + 0.5)
  return { half = half, size = size, residual = size - want }
end

--- The crop in force. `residual` is reported rather than minimised -- it is a diagnostic the
--- probe prints, not a thing to optimise against (see OCCLUDE).
function Look.ChooseCrop(width)
  return Look.CropAt(width, math.floor(ICON_FILE_SIZE * Look.OCCLUDE / 2 + 0.5))
end

--- The crop is snapped to whole texels about the file's centre, so the crop's own centre is
--- exactly the file's and only the DRAW size can round.
--- `half` overrides the search with an explicit half-crop in texels; the probe passes one to
--- lay the search's pick beside its neighbours. Product code omits it.
function Look.IconEscape(fileID, width, half)
  local crop = half and Look.CropAt(width, half) or Look.ChooseCrop(width)
  local centre = ICON_FILE_SIZE / 2
  local lo = (centre - crop.half) / ICON_FILE_SIZE
  local hi = (centre + crop.half) / ICON_FILE_SIZE
  return CreateTextureMarkup(fileID, ICON_FILE_SIZE, ICON_FILE_SIZE, crop.size, crop.size,
    lo, hi, lo, hi, 0, 0), crop
end

--- How hard a mark presses, beyond being lit at all. `urgent` is the only level above plain
--- and it means "this one outranks the ordinary reading" -- a resource actively being wasted,
--- not merely a button that is available.
---
--- It PULSES rather than bounces, and the choice is not cosmetic: a translation is an offset
--- in absolute units, so it would need re-arming on every icon-size change -- the exact bug
--- class that left the mark at its old size until `OnSizeChanged` fixed it. A scale is
--- proportional and immune. The keyword says the MEANING so the drawing can be retuned
--- without touching a rule.
Look.PULSE_SECONDS = 0.45
Look.PULSE_SCALE = 1.35

function Look.Pulse(region)
  local group = region:CreateAnimationGroup()
  local out = group:CreateAnimation("Scale")
  out:SetScaleFrom(1, 1)
  out:SetScaleTo(Look.PULSE_SCALE, Look.PULSE_SCALE)
  out:SetDuration(Look.PULSE_SECONDS / 2)
  out:SetOrder(1)
  out:SetSmoothing("IN_OUT")
  local back = group:CreateAnimation("Scale")
  back:SetScaleFrom(Look.PULSE_SCALE, Look.PULSE_SCALE)
  back:SetScaleTo(1, 1)
  back:SetDuration(Look.PULSE_SECONDS / 2)
  back:SetOrder(2)
  back:SetSmoothing("IN_OUT")
  group:SetLooping("REPEAT")
  return group
end

--- One looping turn, armed at build and never started on a threshold. A count's crossing is
--- never observed; the mark simply spins under the occluder the whole time.
function Look.Spin(region)
  local group = region:CreateAnimationGroup()
  local rotation = group:CreateAnimation("Rotation")
  rotation:SetDegrees(-360)
  rotation:SetDuration(Look.SPIN_SECONDS)
  group:SetLooping("REPEAT")
  group:Play()
  return group
end
