-- The one look both sinks draw: a hexagon outline centred in the icon, spinning.
--
-- The gate tints the white master; the count names a baked file, because an inline texture
-- escape cannot be tinted at runtime. Media/ is generated by tool/gen_media.py.

local _, ns = ...

local Look = {}
ns.Look = Look

Look.DEFAULT = "yellow"
Look.FRACTION = 0.72
Look.SPIN_SECONDS = 3

local PALETTE = {
  white = { 1.00, 1.00, 1.00 },
  yellow = { 1.00, 0.82, 0.25 },
  red = { 1.00, 0.32, 0.32 },
  green = { 0.43, 0.91, 0.50 },
  blue = { 0.38, 0.69, 1.00 },
  purple = { 0.77, 0.52, 1.00 },
  orange = { 1.00, 0.58, 0.25 },
  cyan = { 0.37, 0.92, 0.91 },
}

Look.PALETTE = PALETTE

function Look.IsColor(name)
  return PALETTE[name] ~= nil
end

function Look.Names()
  local names = {}
  for name in pairs(PALETTE) do names[#names + 1] = name end
  table.sort(names)
  return names
end

function Look.Rgb(name)
  return PALETTE[name] or PALETTE[Look.DEFAULT]
end

--- The gate tints the white master, so a gate glow may take any value in the palette without
--- a second file.
Look.MASTER = "Interface\\AddOns\\SmartGlo\\Media\\hex-white"

--- The count sink can only NAME a file, so its hue is whichever one was baked.
function Look.File(name)
  if PALETTE[name] == nil then name = Look.DEFAULT end
  return "Interface\\AddOns\\SmartGlo\\Media\\hex-" .. name
end

--- One looping turn, never started on a threshold: the count's crossing is never observed,
--- so the animation runs permanently and the mark arrives already in motion.
function Look.Spin(region)
  local group = region:CreateAnimationGroup()
  local rotation = group:CreateAnimation("Rotation")
  rotation:SetDegrees(-360)
  rotation:SetDuration(Look.SPIN_SECONDS)
  group:SetLooping("REPEAT")
  group:Play()
  return group
end
